[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "diamond milk life enact romance funny album eight patient aerobic curve notice scale sister siren nest december grape arrange menu vacuum dirt dance suffer"
